language: node_js

node_js:
  - "6"

env:
  - CXX=g++-4.8

sudo: false

script:
  - "grunt build"
  - "make test"

branches:
  only:
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
